//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADataTestVichara.DBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Order = new HashSet<Order>();
            this.Order1 = new HashSet<Order>();
        }
    
        public int ContactID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
    }
}
